services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
